services:
    broker:
        image: rabbitmq:3.11-management
        ports:
            - "5672:5672"
            - "15672:15672"
    producer:
        build:
            context: ../dotnet-sdk-tail
        volumes:
            - ./producer:/source
    consumer:
        build:
            context: ../dotnet-sdk-tail
        volumes:
            - ./consumer:/source
