services:
    broker:
        image: rabbitmq:3.11-management
        ports:
            - "5672:5672"
            - "15672:15672"
    producer:
        build:
            context: ../dotnet-sdk-tail
        volumes:
            - ./producer:/source
    consumer-a:
        build:
            context: ../dotnet-sdk-tail
        volumes:
            - ./consumer-a:/source
    consumer-b:
        build:
            context: ../dotnet-sdk-tail
        volumes:
            - ./consumer-b:/source
